CREATE TABLE `%prefix%admins` (
  `ID` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `username` varchar(50) NOT NULL UNIQUE KEY,
  `password` varchar(255) NOT NULL,
  `salt` varchar(255) NOT NULL DEFAULT '',
  `name` varchar(255) NOT NULL,
  `email` varchar(80) NOT NULL UNIQUE KEY,
  `language` varchar(255) NOT NULL DEFAULT '',
  `rights` longtext NOT NULL,
  `notifications` longtext NOT NULL,
  `tfa` varchar(255) NOT NULL DEFAULT 'none',
  `hide_sidebar` int(1) NOT NULL DEFAULT '0',
  `notes` longtext NOT NULL,
  `online` int(1) NOT NULL DEFAULT '0',
  `call_info` longtext NOT NULL,
  `widgets` longtext NOT NULL,
  `last_sign` int(11) NOT NULL DEFAULT '0',
  `sa` longtext NOT NULL,
  `sat` varchar(255) NOT NULL DEFAULT '',
  `api_key` varchar(255) NOT NULL DEFAULT '',
  `tfa_second` varchar(255) NOT NULL DEFAULT '',
  `tfa_valid` int(11) NOT NULL DEFAULT '0',
  `open_menu` int(1) NOT NULL DEFAULT '1',
  `avatar` varchar(255) NOT NULL DEFAULT '',
  `per_page` int(11) NOT NULL DEFAULT '25'
);